"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _project_list from './project-list.bones.json'

registerBones({
  "project-list": _project_list,
})
